### PR TITLE
fzn2feat Features

### PR DESCRIPTION
**Pull request by SeppiaBrilla**
Hi,
I just made 2 scripts to create the feature file from an essence instance. I have also pushed some of the features I have made using this method. The scripts rely on the fzn2feat program that can be downloaded [here](https://github.com/CP-Unibo/mzn2feat)

### CODE REVIEW

**Comment by ozgurakgun** [comment]
thanks! fyi @SN1683

**Comment by ozgurakgun** [comment]
I noticed after merging @SeppiaBrilla - so you have features for each of the models? Is that right?

This is a minor issue, but can you change the filename from:

fnz2feat_01_compact.eprime_ab4f577a3135171bdddeaef5c327af05.param.json

to

01_compact.eprime_ab4f577a3135171bdddeaef5c327af05.fzn2feat.json

please?

**Comment by SeppiaBrilla** [comment]
Yes, each model has it's set of features but they have only been computed via chuffed. I can rename the files but shouldn't we have some kind of way to easily tell what they are from the file name?

**Comment by ozgurakgun** [comment]
the filename I was suggesting would mean `X.stats.json` always has a corresponding `X.fzn2feat.json` that contains the features, does that make sense?

**Pull request merged**
